// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduPYixM7LOfQHAhy3yggb4cVIfcMXa7A',
    appId: '1:719175778068:web:88e31677259a477d93cc01',
    messagingSenderId: '719175778068',
    projectId: 'marketa-admin',
    authDomain: 'marketa-admin.firebaseapp.com',
    storageBucket: 'marketa-admin.firebasestorage.app',
    measurementId: 'G-77KEWNG6SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sb-Vmq-hTz_2DwwA6eYqDqPT-Lrv5oo',
    appId: '1:719175778068:android:8d3cee47015d706e93cc01',
    messagingSenderId: '719175778068',
    projectId: 'marketa-admin',
    storageBucket: 'marketa-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz7ZWC0M6E0dnjHwl593CNzk2zc5Ht7oM',
    appId: '1:719175778068:ios:35473eaed6692f0693cc01',
    messagingSenderId: '719175778068',
    projectId: 'marketa-admin',
    storageBucket: 'marketa-admin.firebasestorage.app',
    iosBundleId: 'com.example.marketaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz7ZWC0M6E0dnjHwl593CNzk2zc5Ht7oM',
    appId: '1:719175778068:ios:35473eaed6692f0693cc01',
    messagingSenderId: '719175778068',
    projectId: 'marketa-admin',
    storageBucket: 'marketa-admin.firebasestorage.app',
    iosBundleId: 'com.example.marketaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCduPYixM7LOfQHAhy3yggb4cVIfcMXa7A',
    appId: '1:719175778068:web:1bbf5689665f65e493cc01',
    messagingSenderId: '719175778068',
    projectId: 'marketa-admin',
    authDomain: 'marketa-admin.firebaseapp.com',
    storageBucket: 'marketa-admin.firebasestorage.app',
    measurementId: 'G-3PT2VZL5KZ',
  );
}
